use crate::models::layers::military_base::{MilitaryBase};
use crate::models::layers::nuclear_plant::{NuclearPlant};
use crate::models::layers::pipeline::{Capacity, Pipeline, PipelineType};
use crate::models::layers::strait::{Importance, Strait, StraitType};

pub fn get_pipelines() -> Vec<Pipeline> {
    vec![
        Pipeline {
            id: "nordstream-2".into(),
            name: "Nord Stream 2".into(),
            coordinates: vec![
                [28.75, 59.33],
                [26.5, 59.5],
                [24.0, 59.2],
                [20.5, 58.5],
                [17.0, 55.5],
                [14.5, 54.5],
                [13.66, 54.14],
            ],
            pipeline_type: PipelineType::Gas,
            capacity: Some(Capacity::BcmPerYear(55.0)),
            owner: "Gazprom".into(),
            operational_since: None,
        },
        Pipeline {
            id: "nordstream-1".into(),
            name: "Nord Stream 1".into(),
            coordinates: vec![
                [28.75, 59.33],
                [26.5, 59.5],
                [24.0, 59.2],
                [20.5, 58.5],
                [17.0, 55.5],
                [14.5, 54.5],
                [13.66, 54.14],
            ],
            pipeline_type: PipelineType::Gas,
            capacity: Some(Capacity::BcmPerYear(55.0)),
            owner: "Gazprom".into(),
            operational_since: Some(2011),
        },
        Pipeline {
            id: "turkstream".into(),
            name: "TurkStream".into(),
            coordinates: vec![
                [38.95, 44.62],
                [35.0, 43.5],
                [32.0, 42.5],
                [29.0, 41.8],
                [28.68, 41.04],
            ],
            pipeline_type: PipelineType::Gas,
            capacity: Some(Capacity::BcmPerYear(31.5)),
            owner: "Gazprom / Botaş".into(),
            operational_since: Some(2020),
        },
        Pipeline {
            id: "druzhba".into(),
            name: "Druzhba Pipeline".into(),
            coordinates: vec![
                [52.26, 54.87],
                [45.0, 53.0],
                [37.62, 55.75],
                [30.5, 53.9],
                [24.0, 52.2],
                [14.55, 52.52],
            ],
            pipeline_type: PipelineType::Oil,
            capacity: Some(Capacity::BarrelsPerDay(1_400_000)),
            owner: "Transneft".into(),
            operational_since: Some(1964),
        },
    ]
}

pub fn get_straits() -> Vec<Strait> {
    vec![
        Strait {
            id: "hormuz".into(),
            name: "Strait of Hormuz".into(),
            coordinates: [56.27, 26.59],
            strait_type: StraitType::Natural,
            controlled_by: vec!["IR".into(), "OM".into(), "AE".into()],
            connects: ["Persian Gulf".into(), "Gulf of Oman".into()],
            traffic_volume: Some("21M barrels/day".into()),
            strategic_importance: Importance::Critical,
            notes: None,
        },
        Strait {
            id: "malacca".into(),
            name: "Strait of Malacca".into(),
            coordinates: [100.0, 4.0],
            strait_type: StraitType::Natural,
            controlled_by: vec!["MY".into(), "SG".into(), "ID".into()],
            connects: ["Indian Ocean".into(), "South China Sea".into()],
            traffic_volume: Some("25% of global trade".into()),
            strategic_importance: Importance::Critical,
            notes: None,
        },
        Strait {
            id: "suez".into(),
            name: "Suez Canal".into(),
            coordinates: [32.34, 30.46],
            strait_type: StraitType::Canal,
            controlled_by: vec!["EG".into()],
            connects: ["Mediterranean Sea".into(), "Red Sea".into()],
            traffic_volume: Some("12% of global trade".into()),
            strategic_importance: Importance::Critical,
            notes: None,
        },
        Strait {
            id: "panama".into(),
            name: "Panama Canal".into(),
            coordinates: [-79.92, 9.08],
            strait_type: StraitType::Canal,
            controlled_by: vec!["PA".into()],
            connects: ["Atlantic Ocean".into(), "Pacific Ocean".into()],
            traffic_volume: Some("5% of global trade".into()),
            strategic_importance: Importance::High,
            notes: None,
        },
        Strait {
            id: "bosphorus".into(),
            name: "Bosphorus Strait".into(),
            coordinates: [29.05, 41.1],
            strait_type: StraitType::Natural,
            controlled_by: vec!["TR".into()],
            connects: ["Black Sea".into(), "Sea of Marmara".into()],
            traffic_volume: None,
            strategic_importance: Importance::High,
            notes: Some("Montreux Convention 1936".into()),
        },
        Strait {
            id: "gibraltar".into(),
            name: "Strait of Gibraltar".into(),
            coordinates: [-5.6, 35.96],
            strait_type: StraitType::Natural,
            controlled_by: vec!["ES".into(), "MA".into(), "GB".into()],
            connects: ["Atlantic Ocean".into(), "Mediterranean Sea".into()],
            traffic_volume: None,
            strategic_importance: Importance::High,
            notes: None,
        },
        Strait {
            id: "bab-el-mandeb".into(),
            name: "Bab el-Mandeb".into(),
            coordinates: [43.33, 12.58],
            strait_type: StraitType::Natural,
            controlled_by: vec!["YE".into(), "DJ".into(), "ER".into()],
            connects: ["Red Sea".into(), "Gulf of Aden".into()],
            traffic_volume: Some("4.8M barrels/day".into()),
            strategic_importance: Importance::Critical,
            notes: None,
        },
    ]
}

pub fn get_military_bases() -> Vec<MilitaryBase> {
    vec![
        MilitaryBase {
            id: "ramstein".into(),
            name: "Ramstein Air Base".into(),
            coordinates: [7.60, 49.44],
            country: "DE".into(),
            operator: "US".into(),
            personnel: Some(9000),
            notes: Some("USAFE headquarters".into()),
        },
        MilitaryBase {
            id: "landstuhl".into(),
            name: "Landstuhl Regional Medical Center".into(),
            coordinates: [7.57, 49.40],
            country: "DE".into(),
            operator: "US".into(),
            personnel: Some(3000),
            notes: Some("Largest US military hospital overseas".into()),
        },
        MilitaryBase {
            id: "spangdahlem".into(),
            name: "Spangdahlem Air Base".into(),
            coordinates: [6.69, 49.98],
            country: "DE".into(),
            operator: "US".into(),
            personnel: Some(4000),
            notes: None,
        },
        MilitaryBase {
            id: "grafenwoehr".into(),
            name: "Grafenwöhr Training Area".into(),
            coordinates: [11.92, 49.69],
            country: "DE".into(),
            operator: "US".into(),
            personnel: Some(15000),
            notes: Some("Largest US Army training area in Europe".into()),
        },
        MilitaryBase {
            id: "stuttgart".into(),
            name: "US Army Garrison Stuttgart".into(),
            coordinates: [9.10, 48.69],
            country: "DE".into(),
            operator: "US".into(),
            personnel: Some(6000),
            notes: Some("EUCOM & AFRICOM headquarters".into()),
        },
        MilitaryBase {
            id: "aviano".into(),
            name: "Aviano Air Base".into(),
            coordinates: [12.59, 46.03],
            country: "IT".into(),
            operator: "US".into(),
            personnel: Some(4500),
            notes: None,
        },
        MilitaryBase {
            id: "naples".into(),
            name: "Naval Support Activity Naples".into(),
            coordinates: [14.19, 40.82],
            country: "IT".into(),
            operator: "US".into(),
            personnel: Some(6000),
            notes: Some("US Naval Forces Europe headquarters".into()),
        },
        MilitaryBase {
            id: "sigonella".into(),
            name: "Naval Air Station Sigonella".into(),
            coordinates: [14.92, 37.40],
            country: "IT".into(),
            operator: "US".into(),
            personnel: Some(4000),
            notes: Some("Hub for Mediterranean operations".into()),
        },
        MilitaryBase {
            id: "vicenza".into(),
            name: "Caserma Ederle".into(),
            coordinates: [11.54, 45.55],
            country: "IT".into(),
            operator: "US".into(),
            personnel: Some(4500),
            notes: Some("173rd Airborne Brigade".into()),
        },
        MilitaryBase {
            id: "rota".into(),
            name: "Naval Station Rota".into(),
            coordinates: [-6.35, 36.64],
            country: "ES".into(),
            operator: "US".into(),
            personnel: Some(3000),
            notes: Some("Aegis Ballistic Missile Defense".into()),
        },
        MilitaryBase {
            id: "moron".into(),
            name: "Morón Air Base".into(),
            coordinates: [-5.62, 37.17],
            country: "ES".into(),
            operator: "US".into(),
            personnel: Some(500),
            notes: Some("Forward operating site".into()),
        },
        MilitaryBase {
            id: "lajes".into(),
            name: "Lajes Field".into(),
            coordinates: [-27.09, 38.76],
            country: "PT".into(),
            operator: "US".into(),
            personnel: Some(650),
            notes: Some("Azores, transatlantic staging".into()),
        },
        MilitaryBase {
            id: "raf-lakenheath".into(),
            name: "RAF Lakenheath".into(),
            coordinates: [0.56, 52.41],
            country: "GB".into(),
            operator: "US".into(),
            personnel: Some(4500),
            notes: Some("Largest USAF base in UK".into()),
        },
        MilitaryBase {
            id: "raf-mildenhall".into(),
            name: "RAF Mildenhall".into(),
            coordinates: [0.49, 52.36],
            country: "GB".into(),
            operator: "US".into(),
            personnel: Some(3000),
            notes: Some("Air refueling wing".into()),
        },
        MilitaryBase {
            id: "raf-fairford".into(),
            name: "RAF Fairford".into(),
            coordinates: [-1.79, 51.68],
            country: "GB".into(),
            operator: "US".into(),
            personnel: Some(500),
            notes: Some("Bomber forward operating location".into()),
        },
        MilitaryBase {
            id: "souda-bay".into(),
            name: "Naval Support Activity Souda Bay".into(),
            coordinates: [24.09, 35.49],
            country: "GR".into(),
            operator: "US".into(),
            personnel: Some(1000),
            notes: Some("Deep water port, Crete".into()),
        },
        MilitaryBase {
            id: "incirlik".into(),
            name: "Incirlik Air Base".into(),
            coordinates: [35.43, 37.00],
            country: "TR".into(),
            operator: "US/TR".into(),
            personnel: Some(5000),
            notes: Some("Nuclear weapons storage suspected".into()),
        },
        MilitaryBase {
            id: "izmir".into(),
            name: "Izmir Air Station".into(),
            coordinates: [27.14, 38.42],
            country: "TR".into(),
            operator: "US".into(),
            personnel: Some(2000),
            notes: Some("NATO Allied Air Component Command".into()),
        },
        MilitaryBase {
            id: "thule".into(),
            name: "Thule Air Base".into(),
            coordinates: [-68.70, 76.53],
            country: "GL".into(),
            operator: "US".into(),
            personnel: Some(600),
            notes: Some("Northernmost US base, missile warning".into()),
        },
        MilitaryBase {
            id: "keflavik".into(),
            name: "Naval Air Station Keflavik".into(),
            coordinates: [-22.60, 63.98],
            country: "IS".into(),
            operator: "US".into(),
            personnel: Some(400),
            notes: Some("North Atlantic surveillance".into()),
        },

        // Middle East
        MilitaryBase {
            id: "al-udeid".into(),
            name: "Al Udeid Air Base".into(),
            coordinates: [51.31, 25.12],
            country: "QA".into(),
            operator: "US".into(),
            personnel: Some(10000),
            notes: Some("CENTCOM forward HQ, largest in Middle East".into()),
        },
        MilitaryBase {
            id: "al-dhafra".into(),
            name: "Al Dhafra Air Base".into(),
            coordinates: [54.55, 24.25],
            country: "AE".into(),
            operator: "US/AE".into(),
            personnel: Some(5000),
            notes: Some("ISR and refueling hub".into()),
        },
        MilitaryBase {
            id: "bahrain".into(),
            name: "Naval Support Activity Bahrain".into(),
            coordinates: [50.60, 26.24],
            country: "BH".into(),
            operator: "US".into(),
            personnel: Some(7000),
            notes: Some("US Fifth Fleet headquarters".into()),
        },
        MilitaryBase {
            id: "ali-al-salem".into(),
            name: "Ali Al Salem Air Base".into(),
            coordinates: [47.52, 29.35],
            country: "KW".into(),
            operator: "US".into(),
            personnel: Some(5000),
            notes: Some("Primary hub for Iraq/Afghanistan ops".into()),
        },
        MilitaryBase {
            id: "camp-arifjan".into(),
            name: "Camp Arifjan".into(),
            coordinates: [48.13, 28.93],
            country: "KW".into(),
            operator: "US".into(),
            personnel: Some(8000),
            notes: Some("Army Central headquarters".into()),
        },
        MilitaryBase {
            id: "eskan-village".into(),
            name: "Eskan Village".into(),
            coordinates: [46.77, 24.57],
            country: "SA".into(),
            operator: "US".into(),
            personnel: Some(500),
            notes: Some("Low profile presence".into()),
        },
        MilitaryBase {
            id: "prince-sultan".into(),
            name: "Prince Sultan Air Base".into(),
            coordinates: [47.58, 24.07],
            country: "SA".into(),
            operator: "US".into(),
            personnel: Some(2500),
            notes: Some("Reactivated 2019".into()),
        },
        MilitaryBase {
            id: "al-minhad".into(),
            name: "Al Minhad Air Base".into(),
            coordinates: [55.37, 25.03],
            country: "AE".into(),
            operator: "US/AE".into(),
            personnel: Some(500),
            notes: None,
        },

        // Africa
        MilitaryBase {
            id: "djibouti".into(),
            name: "Camp Lemonnier".into(),
            coordinates: [43.15, 11.55],
            country: "DJ".into(),
            operator: "US".into(),
            personnel: Some(4000),
            notes: Some("Only permanent US base in Africa".into()),
        },
        MilitaryBase {
            id: "niamey".into(),
            name: "Air Base 101 Niamey".into(),
            coordinates: [2.18, 13.48],
            country: "NE".into(),
            operator: "US".into(),
            personnel: Some(800),
            notes: Some("Drone operations".into()),
        },
        MilitaryBase {
            id: "agadez".into(),
            name: "Air Base 201 Agadez".into(),
            coordinates: [8.00, 16.97],
            country: "NE".into(),
            operator: "US".into(),
            personnel: Some(1100),
            notes: Some("$110M drone base".into()),
        },

        // Asia-Pacific
        MilitaryBase {
            id: "camp-humphreys".into(),
            name: "Camp Humphreys".into(),
            coordinates: [127.03, 36.96],
            country: "KR".into(),
            operator: "US".into(),
            personnel: Some(36000),
            notes: Some("Largest overseas US base".into()),
        },
        MilitaryBase {
            id: "osan".into(),
            name: "Osan Air Base".into(),
            coordinates: [127.03, 37.09],
            country: "KR".into(),
            operator: "US".into(),
            personnel: Some(8000),
            notes: Some("51st Fighter Wing".into()),
        },
        MilitaryBase {
            id: "kunsan".into(),
            name: "Kunsan Air Base".into(),
            coordinates: [126.62, 35.90],
            country: "KR".into(),
            operator: "US".into(),
            personnel: Some(2500),
            notes: Some("8th Fighter Wing".into()),
        },
        MilitaryBase {
            id: "yokosuka".into(),
            name: "Fleet Activities Yokosuka".into(),
            coordinates: [139.65, 35.28],
            country: "JP".into(),
            operator: "US".into(),
            personnel: Some(27000),
            notes: Some("7th Fleet HQ, forward-deployed carrier".into()),
        },
        MilitaryBase {
            id: "yokota".into(),
            name: "Yokota Air Base".into(),
            coordinates: [139.35, 35.75],
            country: "JP".into(),
            operator: "US".into(),
            personnel: Some(14000),
            notes: Some("USFJ headquarters".into()),
        },
        MilitaryBase {
            id: "kadena".into(),
            name: "Kadena Air Base".into(),
            coordinates: [127.77, 26.35],
            country: "JP".into(),
            operator: "US".into(),
            personnel: Some(18000),
            notes: Some("Largest USAF base in Pacific, Okinawa".into()),
        },
        MilitaryBase {
            id: "camp-foster".into(),
            name: "Camp Foster".into(),
            coordinates: [127.76, 26.31],
            country: "JP".into(),
            operator: "US".into(),
            personnel: Some(8000),
            notes: Some("Marine Corps, Okinawa".into()),
        },
        MilitaryBase {
            id: "futenma".into(),
            name: "Marine Corps Air Station Futenma".into(),
            coordinates: [127.76, 26.27],
            country: "JP".into(),
            operator: "US".into(),
            personnel: Some(4000),
            notes: Some("Controversial, relocation planned".into()),
        },
        MilitaryBase {
            id: "sasebo".into(),
            name: "Fleet Activities Sasebo".into(),
            coordinates: [129.72, 33.16],
            country: "JP".into(),
            operator: "US".into(),
            personnel: Some(6000),
            notes: Some("Amphibious force staging".into()),
        },
        MilitaryBase {
            id: "iwakuni".into(),
            name: "Marine Corps Air Station Iwakuni".into(),
            coordinates: [132.24, 34.14],
            country: "JP".into(),
            operator: "US".into(),
            personnel: Some(15000),
            notes: Some("F-35B deployment".into()),
        },
        MilitaryBase {
            id: "misawa".into(),
            name: "Misawa Air Base".into(),
            coordinates: [141.37, 40.70],
            country: "JP".into(),
            operator: "US".into(),
            personnel: Some(5500),
            notes: Some("35th Fighter Wing".into()),
        },
        MilitaryBase {
            id: "guam-andersen".into(),
            name: "Andersen Air Force Base".into(),
            coordinates: [144.93, 13.58],
            country: "GU".into(),
            operator: "US".into(),
            personnel: Some(4000),
            notes: Some("B-52/B-2 bomber operations".into()),
        },
        MilitaryBase {
            id: "guam-naval".into(),
            name: "Naval Base Guam".into(),
            coordinates: [144.65, 13.45],
            country: "GU".into(),
            operator: "US".into(),
            personnel: Some(6000),
            notes: Some("Submarine base, major expansion planned".into()),
        },
        MilitaryBase {
            id: "diego-garcia".into(),
            name: "Naval Support Facility Diego Garcia".into(),
            coordinates: [72.41, -7.32],
            country: "IO".into(),
            operator: "US/UK".into(),
            personnel: Some(3000),
            notes: Some("Strategic Indian Ocean hub".into()),
        },
        MilitaryBase {
            id: "darwin".into(),
            name: "Robertson Barracks".into(),
            coordinates: [131.05, -12.43],
            country: "AU".into(),
            operator: "US/AU".into(),
            personnel: Some(2500),
            notes: Some("Marine rotational force".into()),
        },
        MilitaryBase {
            id: "clark".into(),
            name: "Clark Air Base".into(),
            coordinates: [120.56, 15.19],
            country: "PH".into(),
            operator: "US".into(),
            personnel: Some(500),
            notes: Some("EDCA site, rotational access".into()),
        },
        MilitaryBase {
            id: "subic".into(),
            name: "Subic Bay".into(),
            coordinates: [120.28, 14.79],
            country: "PH".into(),
            operator: "US".into(),
            personnel: Some(300),
            notes: Some("EDCA site, ship visits".into()),
        },
        MilitaryBase {
            id: "changi".into(),
            name: "Changi Naval Base".into(),
            coordinates: [104.03, 1.32],
            country: "SG".into(),
            operator: "US/SG".into(),
            personnel: Some(200),
            notes: Some("Littoral combat ship rotation".into()),
        },

        // Americas
        MilitaryBase {
            id: "guantanamo".into(),
            name: "Naval Station Guantanamo Bay".into(),
            coordinates: [-75.13, 19.90],
            country: "CU".into(),
            operator: "US".into(),
            personnel: Some(6000),
            notes: Some("Oldest overseas US base".into()),
        },
        MilitaryBase {
            id: "soto-cano".into(),
            name: "Soto Cano Air Base".into(),
            coordinates: [-87.62, 14.38],
            country: "HN".into(),
            operator: "US".into(),
            personnel: Some(1300),
            notes: Some("Joint Task Force Bravo".into()),
        },
        MilitaryBase {
            id: "curacao".into(),
            name: "FOL Curaçao".into(),
            coordinates: [-68.96, 12.17],
            country: "CW".into(),
            operator: "US".into(),
            personnel: Some(200),
            notes: Some("Counter-narcotics".into()),
        },
        MilitaryBase {
            id: "aruba".into(),
            name: "FOL Aruba".into(),
            coordinates: [-70.01, 12.51],
            country: "AW".into(),
            operator: "US".into(),
            personnel: Some(200),
            notes: Some("Counter-narcotics".into()),
        },
    ]
}

pub fn get_nuclear_plants() -> Vec<NuclearPlant> {
    vec![
        NuclearPlant {
            id: "zaporizhzhia".into(),
            name: "Zaporizhzhia Nuclear Power Plant".into(),
            coordinates: [34.59, 47.51],
            country: "UA".into(),
            capacity_mw: Some(5700),
            reactors: Some(6),
            operator: None,
            notes: Some("Largest nuclear plant in Europe".into()),
        },
        NuclearPlant {
            id: "fukushima".into(),
            name: "Fukushima Daiichi".into(),
            coordinates: [141.03, 37.42],
            country: "JP".into(),
            capacity_mw: None,
            reactors: None,
            operator: Some("TEPCO".into()),
            notes: Some("2011 meltdown".into()),
        },
        NuclearPlant {
            id: "bushehr".into(),
            name: "Bushehr Nuclear Plant".into(),
            coordinates: [50.89, 28.83],
            country: "IR".into(),
            capacity_mw: Some(1000),
            reactors: Some(1),
            operator: Some("Rosatom".into()),
            notes: None,
        },
        NuclearPlant {
            id: "barakah".into(),
            name: "Barakah Nuclear Plant".into(),
            coordinates: [52.19, 23.95],
            country: "AE".into(),
            capacity_mw: Some(5600),
            reactors: Some(4),
            operator: Some("ENEC".into()),
            notes: Some("First Arab nuclear plant".into()),
        },
    ]
}