use crate::models::layers::military_base::{BaseStatus, BaseType, MilitaryBase, MilitaryBranch};
use crate::models::layers::nuclear_plant::{NuclearPlant, PlantStatus};
use crate::models::layers::pipeline::{Capacity, Pipeline, PipelineStatus, PipelineType};
use crate::models::layers::strait::{Importance, Strait, StraitType};

pub fn get_pipelines() -> Vec<Pipeline> {
    vec![
        Pipeline {
            id: "nordstream-2".into(),
            name: "Nord Stream 2".into(),
            coordinates: vec![
                [28.75, 59.33],
                [26.5, 59.5],
                [24.0, 59.2],
                [20.5, 58.5],
                [17.0, 55.5],
                [14.5, 54.5],
                [13.66, 54.14],
            ],
            status: PipelineStatus::Damaged,
            pipeline_type: PipelineType::Gas,
            capacity: Some(Capacity::BcmPerYear(55.0)),
            owner: "Gazprom".into(),
            operational_since: None,
        },
        Pipeline {
            id: "nordstream-1".into(),
            name: "Nord Stream 1".into(),
            coordinates: vec![
                [28.75, 59.33],
                [26.5, 59.5],
                [24.0, 59.2],
                [20.5, 58.5],
                [17.0, 55.5],
                [14.5, 54.5],
                [13.66, 54.14],
            ],
            status: PipelineStatus::Damaged,
            pipeline_type: PipelineType::Gas,
            capacity: Some(Capacity::BcmPerYear(55.0)),
            owner: "Gazprom".into(),
            operational_since: Some(2011),
        },
        Pipeline {
            id: "turkstream".into(),
            name: "TurkStream".into(),
            coordinates: vec![
                [38.95, 44.62],
                [35.0, 43.5],
                [32.0, 42.5],
                [29.0, 41.8],
                [28.68, 41.04],
            ],
            status: PipelineStatus::Active,
            pipeline_type: PipelineType::Gas,
            capacity: Some(Capacity::BcmPerYear(31.5)),
            owner: "Gazprom / Botaş".into(),
            operational_since: Some(2020),
        },
        Pipeline {
            id: "druzhba".into(),
            name: "Druzhba Pipeline".into(),
            coordinates: vec![
                [52.26, 54.87],
                [45.0, 53.0],
                [37.62, 55.75],
                [30.5, 53.9],
                [24.0, 52.2],
                [14.55, 52.52],
            ],
            status: PipelineStatus::Active,
            pipeline_type: PipelineType::Oil,
            capacity: Some(Capacity::BarrelsPerDay(1_400_000)),
            owner: "Transneft".into(),
            operational_since: Some(1964),
        },
    ]
}

pub fn get_straits() -> Vec<Strait> {
    vec![
        Strait {
            id: "hormuz".into(),
            name: "Strait of Hormuz".into(),
            coordinates: [56.27, 26.59],
            strait_type: StraitType::Natural,
            controlled_by: vec!["IR".into(), "OM".into(), "AE".into()],
            connects: ["Persian Gulf".into(), "Gulf of Oman".into()],
            traffic_volume: Some("21M barrels/day".into()),
            strategic_importance: Importance::Critical,
            notes: None,
        },
        Strait {
            id: "malacca".into(),
            name: "Strait of Malacca".into(),
            coordinates: [100.0, 4.0],
            strait_type: StraitType::Natural,
            controlled_by: vec!["MY".into(), "SG".into(), "ID".into()],
            connects: ["Indian Ocean".into(), "South China Sea".into()],
            traffic_volume: Some("25% of global trade".into()),
            strategic_importance: Importance::Critical,
            notes: None,
        },
        Strait {
            id: "suez".into(),
            name: "Suez Canal".into(),
            coordinates: [32.34, 30.46],
            strait_type: StraitType::Canal,
            controlled_by: vec!["EG".into()],
            connects: ["Mediterranean Sea".into(), "Red Sea".into()],
            traffic_volume: Some("12% of global trade".into()),
            strategic_importance: Importance::Critical,
            notes: None,
        },
        Strait {
            id: "panama".into(),
            name: "Panama Canal".into(),
            coordinates: [-79.92, 9.08],
            strait_type: StraitType::Canal,
            controlled_by: vec!["PA".into()],
            connects: ["Atlantic Ocean".into(), "Pacific Ocean".into()],
            traffic_volume: Some("5% of global trade".into()),
            strategic_importance: Importance::High,
            notes: None,
        },
        Strait {
            id: "bosphorus".into(),
            name: "Bosphorus Strait".into(),
            coordinates: [29.05, 41.1],
            strait_type: StraitType::Natural,
            controlled_by: vec!["TR".into()],
            connects: ["Black Sea".into(), "Sea of Marmara".into()],
            traffic_volume: None,
            strategic_importance: Importance::High,
            notes: Some("Montreux Convention 1936".into()),
        },
        Strait {
            id: "gibraltar".into(),
            name: "Strait of Gibraltar".into(),
            coordinates: [-5.6, 35.96],
            strait_type: StraitType::Natural,
            controlled_by: vec!["ES".into(), "MA".into(), "GB".into()],
            connects: ["Atlantic Ocean".into(), "Mediterranean Sea".into()],
            traffic_volume: None,
            strategic_importance: Importance::High,
            notes: None,
        },
        Strait {
            id: "bab-el-mandeb".into(),
            name: "Bab el-Mandeb".into(),
            coordinates: [43.33, 12.58],
            strait_type: StraitType::Natural,
            controlled_by: vec!["YE".into(), "DJ".into(), "ER".into()],
            connects: ["Red Sea".into(), "Gulf of Aden".into()],
            traffic_volume: Some("4.8M barrels/day".into()),
            strategic_importance: Importance::Critical,
            notes: None,
        },
    ]
}

pub fn get_military_bases() -> Vec<MilitaryBase> {
    vec![
        MilitaryBase {
            id: "ramstein".into(),
            name: "Ramstein Air Base".into(),
            coordinates: [7.6, 49.44],
            country: "DE".into(),
            operator: "US".into(),
            branch: MilitaryBranch::AirForce,
            base_type: BaseType::AirBase,
            personnel: Some(9000),
            status: BaseStatus::Active,
            notes: None,
        },
        MilitaryBase {
            id: "diego-garcia".into(),
            name: "Diego Garcia".into(),
            coordinates: [72.41, -7.32],
            country: "IO".into(),
            operator: "US/UK".into(),
            branch: MilitaryBranch::Combined,
            base_type: BaseType::NavalAirBase,
            personnel: None,
            status: BaseStatus::Active,
            notes: Some("Strategic Indian Ocean base".into()),
        },
        MilitaryBase {
            id: "camp-humphreys".into(),
            name: "Camp Humphreys".into(),
            coordinates: [127.03, 36.96],
            country: "KR".into(),
            operator: "US".into(),
            branch: MilitaryBranch::Army,
            base_type: BaseType::ArmyBase,
            personnel: Some(36000),
            status: BaseStatus::Active,
            notes: Some("Largest overseas US base".into()),
        },
        MilitaryBase {
            id: "yokosuka".into(),
            name: "Yokosuka Naval Base".into(),
            coordinates: [139.65, 35.28],
            country: "JP".into(),
            operator: "US".into(),
            branch: MilitaryBranch::Navy,
            base_type: BaseType::NavalBase,
            personnel: None,
            status: BaseStatus::Active,
            notes: Some("7th Fleet HQ".into()),
        },
        MilitaryBase {
            id: "guantanamo".into(),
            name: "Guantanamo Bay".into(),
            coordinates: [-75.13, 19.9],
            country: "CU".into(),
            operator: "US".into(),
            branch: MilitaryBranch::Navy,
            base_type: BaseType::NavalBase,
            personnel: None,
            status: BaseStatus::Active,
            notes: None,
        },
        MilitaryBase {
            id: "al-udeid".into(),
            name: "Al Udeid Air Base".into(),
            coordinates: [51.31, 25.12],
            country: "QA".into(),
            operator: "US/QA".into(),
            branch: MilitaryBranch::AirForce,
            base_type: BaseType::AirBase,
            personnel: None,
            status: BaseStatus::Active,
            notes: Some("CENTCOM forward HQ".into()),
        },
        MilitaryBase {
            id: "sevastopol".into(),
            name: "Sevastopol Naval Base".into(),
            coordinates: [33.52, 44.62],
            country: "UA".into(),
            operator: "RU".into(),
            branch: MilitaryBranch::Navy,
            base_type: BaseType::NavalBase,
            personnel: None,
            status: BaseStatus::Contested,
            notes: Some("Black Sea Fleet HQ".into()),
        },
        MilitaryBase {
            id: "tartus".into(),
            name: "Tartus Naval Facility".into(),
            coordinates: [35.89, 34.89],
            country: "SY".into(),
            operator: "RU".into(),
            branch: MilitaryBranch::Navy,
            base_type: BaseType::NavalBase,
            personnel: None,
            status: BaseStatus::Active,
            notes: Some("Only Russian Mediterranean base".into()),
        },
        MilitaryBase {
            id: "djibouti-cn".into(),
            name: "PLA Support Base Djibouti".into(),
            coordinates: [43.15, 11.59],
            country: "DJ".into(),
            operator: "CN".into(),
            branch: MilitaryBranch::Navy,
            base_type: BaseType::SupportBase,
            personnel: None,
            status: BaseStatus::Active,
            notes: Some("First overseas Chinese base (2017)".into()),
        },
    ]
}

pub fn get_nuclear_plants() -> Vec<NuclearPlant> {
    vec![
        NuclearPlant {
            id: "zaporizhzhia".into(),
            name: "Zaporizhzhia Nuclear Power Plant".into(),
            coordinates: [34.59, 47.51],
            country: "UA".into(),
            capacity_mw: Some(5700),
            reactors: Some(6),
            status: PlantStatus::Occupied,
            operator: None,
            notes: Some("Largest nuclear plant in Europe".into()),
        },
        NuclearPlant {
            id: "fukushima".into(),
            name: "Fukushima Daiichi".into(),
            coordinates: [141.03, 37.42],
            country: "JP".into(),
            capacity_mw: None,
            reactors: None,
            status: PlantStatus::Decommissioning,
            operator: Some("TEPCO".into()),
            notes: Some("2011 meltdown".into()),
        },
        NuclearPlant {
            id: "bushehr".into(),
            name: "Bushehr Nuclear Plant".into(),
            coordinates: [50.89, 28.83],
            country: "IR".into(),
            capacity_mw: Some(1000),
            reactors: Some(1),
            status: PlantStatus::Active,
            operator: Some("Rosatom".into()),
            notes: None,
        },
        NuclearPlant {
            id: "barakah".into(),
            name: "Barakah Nuclear Plant".into(),
            coordinates: [52.19, 23.95],
            country: "AE".into(),
            capacity_mw: Some(5600),
            reactors: Some(4),
            status: PlantStatus::Active,
            operator: Some("ENEC".into()),
            notes: Some("First Arab nuclear plant".into()),
        },
    ]
}